spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: cliente
          uri: lb://cliente-service
          predicates:
            - Path=/api/clientes/**
          filters:
            - RewritePath=/api/clientes/(?<remaining>.*), /api/clientes/${remaining}
        - id: contenedor
          uri: lb://contenedor-service
          predicates:
            - Path=/api/contenedores/**
        - id: camiones
          uri: lb://camion-service
          predicates:
            - Path=/api/camiones/**
        - id: tarifas
          uri: lb://tarifa-service
          predicates:
            - Path=/api/tarifas/**
        - id: ruta
          uri: lb://ruta-service
          predicates:
            - Path=/api/rutas/**
        - id: deposito
          uri: lb://deposito-service
          predicates:
            - Path=/api/depositos/**
        - id: solicitud
          uri: lb://solicitud-service
          predicates:
            - Path=/api/solicitudes/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
