spring:
  application:
    name: solicitud-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/tpi/protocol/openid-connect/certs
          issuer-uri: http://localhost:8088/realms/tpi
  datasource:
    url: jdbc:postgresql://localhost:5432/solicitud_db
    username: solicitud_user
    password: solicitud_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

camion-service:
  url: ${CAMION_SERVICE_URL:http://localhost:8083}

contenedor-service:
  url: ${CONTENEDOR_SERVICE_URL:http://localhost:8082}

---
# docker profile
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://solicitud-db:5432/solicitud_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: solicitud-service
    preferIpAddress: false

camion-service:
  url: http://camion-service:8083

contenedor-service:
  url: http://contenedor-service:8082
