spring:
  application:
    name: solicitud-service
  datasource:
    url: jdbc:postgresql://localhost:5432/solicitud_db
    username: solicitud_user
    password: solicitud_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
# docker profile
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://solicitud-db:5432/solicitud_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
